matrix:
  include:
    - language: python
      python:
        - "2.7"
        - "3.6"
      virtualenv:
        system_site_packages: true
      before_install:
        - pip install pep8
        - pip install pylint
      install:
        - pip install -r src/follow/requirements.txt
      script:
        - "pylint"
        - find . -name \*.py -exec pep8 --ignore=E402 {} +
        #- python src/follow/tests.py
    - language: java
      addons:
        apt:
          packages:
            - oracle-java9-installer
      jdk: oraclejdk9
      script:
        - echo "Java!" && false


    - language: ruby
      rvm:
       - 2.3
      script:
        - echo "Ruby!" && false

    - language: node_js
      node_js:
        - "10"
      script:
        - cd src/skits/ && npm install && npm run test

    - language: php
      php:
        - '5.7'
      script:
        - echo "Php!" && false

    - language: verification
      script:
        - test -d docs
        - test -f README.md
        - test -f LICENSE

