matrix:
  include:
    - lanuage: python
      python:
        - "2.7"
        - "3.6"

      script:
        - echo "Python!"
    - language: java
      script:
          echo: "Java!"


    - language: ruby
      rvm:
       - 2.2
       - jruby
       - rbx-3

    - language: node_js
      node_js:
        - "10"

    - language: php
      php:
        - '7.0'

