matrix:
  include:
    - lanuage: python
      python:
        - "2.7"
        - "3.6"

      script:
        - echo "Python!"
    - language: java
      java:
        - 1.9
      script:
        - echo "Java!"


    - language: ruby
      rvm:
       - 2.5
      script:
        - echo "Ruby!"

    - language: node_js
      node_js:
        - "10"
      script:
        - echo "Node!"

    - language: php
      php:
        - '7.0'
      script:
        - echo "Php!"

