matrix:
  include:
    - lanuage: python
      python:
        - "2.7"
        - "3.6"

      script:
        - echo "Python!"
    - language: java
      addons:
        apt:
          packages:
            - oracle-java9-installer
      jdk: oraclejdk9
      script:
        - echo "Java!"


    - language: ruby
      rvm:
       - 2.5
      script:
        - echo "Ruby!"

    - language: node_js
      node_js:
        - "10"
      script:
        - echo "Node!"

    - language: php
      php:
        - '7.0'
      script:
        - echo "Php!"
    - language: verification
      script:
        - test -d docs
        - test -f README.md
        - test -f LICENSE

