version: '3.3'

networks:
  datanet:
    external: true # Temporaryily external
  skitnet:
    external: true # Temporaryily external
  replynet:
    external: true # Temporaryily external
  authnet:
    external: true # Temporaryily external
  usernet:
    external: true

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: default
    volumes:
      - "./db/mariadb/data:/var/lib/mysql"
      - "./db/mariadb/schema.sql:/docker-entrypoint-initdb.d/schema.sql"
    ports:
      - "3306:3306"
    networks:
      - datanet
  elk:
    image: sebp/elk
    container_name: elasticsearch
    restart: always
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
    networks:
      - datanet
  auth:
    image: skitter/auth:0.0.1
    build:
      dockerfile: Dockerfile
      context: auth/
    ports:
      - 4000:4000
    networks:
      - datanet
      - authnet
  skits:
    image: skitter/skits:0.0.1
    build:
      dockerfile: Dockerfile
      context: skits/
    ports:
       - 7000:7000
    networks:
      - skitnet
      - datanet
  skit-reply:
    image: skitter/reply:0.0.1
    build:
      dockerfile: Dockerfile
      context: skit-reply
    ports:
       - 9000:9000
    networks:
      - replynet
      - datanet
  frontloader:
    image: skitter/front-loader:0.0.1
    build:
      dockerfile: front-loader/Dockerfile
      context: .
    volumes:
        - ./site/dist:/usr/share/nginx/html
    ports:
      - 80:80
    networks:
      - usernet
      - authnet
      - skitnet

