version: '3.3'

networks:
  datanet:
    external: true # Temporaryily external
  skitnet:
    external: true # Temporaryily external

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: default
    volumes:
      - "./db/mariadb/data:/var/lib/mysql"
      - "./db/mariadb/schema.sql:/docker-entrypoint-initdb.d/schema.sql"
    ports:
      - "3306:3306"
    networks:
      - datanet
  elk:
    image: sebp/elk
    container_name: elasticsearch
    restart: always
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
    networks:
      - datanet
  skits:
    image: skit-node
    build:
      dockerfile: Dockerfile
      context: skits/
    ports:
       - 7000:7000
    networks:
      - skitnet
      - datanet
